name: sendMessageToDiscord
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Enviar mensagem para o Discord
        run: curl -i -H "Content-Type: application/json" -d "{\"content\": \"${{ vars.VAR_MESSAGE }}\"}" "${{ secrets.DISCORD_WEBHOOK }}"
