name: testAndre

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Mas que dia bonito!"
      - run: echo "${{ secrets.MY_SECRET }}"
      - run: echo "Olá ${{ vars.MY_VAR }}, bem-vindo/a!"
